name: jamaah_yasinan
description: "Aplikasi Untuk Membantu Pengelolaan Jamaah Yasinan."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.2.8
  hijri_date: ^1.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/kitab/
    - assets/json/surat/
    - assets/json/doa/
    - assets/json/tahlil/
